name: versioning_exam_action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install black ruff # if none requirements.txt file, just install needed ones

    - name: Run Black (code formatting)
      run: black .

    - name: Run Ruff (code quality check)
      run: ruff check .

